- .github/workflows/deploy.yml
- package-lock.json
- package.json
- #2 FEAT: deploy pipeline 설정
<br/>
- gitaction cicd pipeline 설정
<br/>
어떤 변경 사항이 있나요?
<br/>
> [FEAT] deploy pipeline 설정

- src/index.ts
- src/router/authRoutes.ts
- #14 
<br/>
- sns 로그아웃 기능 (세션 삭제, 리다이렉트 URL 반환)
<br/>
어떤 변경 사항이 있나요?
<br/>
> #14 [FEAT] sns 로그아웃 기능

- src/services/schedule.service.ts
- src/utils/openai.ts
- https://github.com/GonggakSim/Backend/issues/24
<br/>
- 주어진 조건에 따라 학습 계획을 GPT Open AI를 통해 추천해주는 기능을 구현
- 사용자가 제공하는 학습 경험, 하루 학습 가능 시간, 시험의 목표, 선호하는 시험 요일 등을 기반으로 최적의 시험 날짜를 추천해준다.
- 'X주 완성 학습 플랜', '시험일자'로 반환된다
<br/>
어떤 변경 사항이 있나요?
<br/>
> #19 FEAT GPT AI 시험 일정 추천 기능

- prisma/migrations/20250119064437_add_fcm_token/migration.sql
- prisma/schema.prisma
- src/dtos/exam.dto.ts
- src/repositories/exam.repository.ts
- src/services/exam.service.ts
- src/utils/fcm.utils.ts
- src/utils/notification.utils.ts
- https://github.com/GonggakSim/Backend/issues/33
<br/>
- FCM 토큰 관리
- 클라이언트로부터 FCM 토큰을 받고 관리한다
- 시험 정보 추가 시 시험 정보가 addExam을 통해 데이터베이스에 저장되고, FCM 토큰이 없으면 DB에서 조회한다.
- notification.utils.ts의 scheduleRandomNotificaiton은 무작위 D-day를 생성하고, node-cron을 통해 알림을 예약한다.
- fcm.utils.ts의 sendFcmNotification이 호출되어 Firebase를 통해 FCM 알림을 전송한다.
<br/>
어떤 변경 사항이 있나요?
<br/>
> [REFACT] FCM 토큰 관리

- package-lock.json
- prisma/migrations/20250118205702_update_user_category/migration.sql
- prisma/migrations/20250119082131_update_user/migration.sql
- prisma/migrations/20250119114148_update_user_cascade/migration.sql
- prisma/schema.prisma
- src/controllers/auth.controller.ts
- src/controllers/consent.controller.ts
- src/dtos/user.dto.ts
- src/middlewares/auth.middleware.ts
- src/repositories/user.repository.ts
- src/routes/authRoutes.ts
- src/services/auth.service.ts
- #32 
<br/>
- 회원탈퇴/로그아웃 실행 시, 사용자 세션 삭제와 데이터 삭제
<br/>
어떤 변경 사항이 있나요?
<br/>
> #32 회원탈퇴 기능

- .github/workflows/deploy-main.yml
<br/>
<br/>
어떤 변경 사항이 있나요?
<br/>
> [FEAT] Update deploy

- build/swagger.yaml
- src/controllers/consent.controller.ts
- src/index.ts
- src/routes/userRoutes.ts
- src/swagger/openapi.yaml
- #49 
<br/>
- 이용약관 선택적 동의 수정, 회원정보 수정 기능 url 수정
<br/>
어떤 변경 사항이 있나요?
<br/>
> #49 회원정보 수정 & 이용약관 동의 선택적 수정

- src/controllers/certificateInquiry.controller.ts
- src/dtos/certificateInquiry.dto.ts
- src/index.ts
- src/repositories/certificateInquiry.repository.ts
- src/services/certificateInquiry.service.ts
- #46 
<br/>
- 전체 자격증 목록 조회 
요청제시 (GET /api/v1/certifications)
- 카테고리별 자격증 목록 조회 
요청 제시 (GET /api/v1/certifications/category/{category})
- 특정 자격증 상세 조회 
요청 제시 (GET /api/v1/certifications/{certificationId})
<br/>
어떤 변경 사항이 있나요?
<br/>
> [FEAT] 자격증 목록 조회 기능 

- src/controllers/schedule.controller.ts
- src/index.ts
- src/routes/scheduleRoutes.ts
- [Feature] 월별 특정 시험 일정 조회 기능 #47 
<br/>
- 월별 특정 시험 일정 조회 기능
- 특정 시험의 아이디(certificationId)의 일정(schedule)을 모두 조회하여 month에 해당하는 일정을 조회
- 요청 예시 (GET /certifications/{certificationId}/schedules/{month})
<br/>
어떤 변경 사항이 있나요?
<br/>
> [FEAT] 월별 특정 시험 일정 조회 기능

- prisma/migrations/20250122052420_remove_fcm_token_from_exam/migration.sql
- prisma/migrations/20250122055322_add_fcm_token/migration.sql
- prisma/schema.prisma
- src/repositories/exam.repository.ts
- src/services/exam.service.ts
- src/utils/fcm.utils.ts
- src/utils/notification.utils.ts
- https://github.com/GonggakSim/Backend/issues/54
<br/>
- 캘린더 리마인드 알림 리팩토링, FCM 토큰 관리 수정
- FCM 토큰 관리 로직 수정
- Prisma 테이블 수정
<br/>
어떤 변경 사항이 있나요?
<br/>
> #54 캘린더 리마인드 알림 리팩토링, FCM 토큰 관리 수정

- package-lock.json
- package.json
- prisma/migrations/20250123130203_modify_the_type_of_notification_fields/migration.sql
- prisma/schema.prisma
- src/controllers/exam.controller.ts
- src/controllers/notification.controller.ts
- src/dtos/exam.dto.ts
- src/dtos/notificationSettings.dto.ts
- src/index.ts
- src/repositories/exam.repository.ts
- src/repositories/notification.repository.ts
- src/services/exam.service.ts
- src/services/notification.service.ts
- src/utils/fcm.utils.ts
- src/utils/notification.utils.ts
- https://github.com/GonggakSim/Backend/issues/54
<br/>
- prisma notification의 필드 타입 변경
- 방해 금지 모드 퀴즈 알림 기능 구현중
- 알림 관련 기능 리팩토링
<br/>
어떤 변경 사항이 있나요?
<br/>
> #54 방해 금지 모드 설정 및 알림 관련 기능 수정

- src/dtos/notificationSettings.dto.ts
- src/repositories/notification.repository.ts
- src/services/notification.service.ts
- src/utils/fcm.utils.ts
- src/utils/notification.utils.ts
- https://github.com/GonggakSim/Backend/issues/58
<br/>
- 방해 금지 시간대 중첩 가능 설정
- FCM 토큰 관리 수정
- 전체 로직 검토 및 수정
<br/>
어떤 변경 사항이 있나요?
<br/>
> #58 방해 금지 모드 로직 수정 및 FCM 토큰 관리

- .github/workflows/deploy-main.yml
<br/>
<br/>
어떤 변경 사항이 있나요?
<br/>
> [REFACT] 배포 환경 업데이트 테스트

- package.json
- scripts/build.ts
<br/>
<br/>
어떤 변경 사항이 있나요?
<br/>
> [REFACT] 배포 형식 cjs로 수정

- src/index.ts
- #(issue 번호) FEAT: 기능명
ex) #17 FEAT: pull request template 작성
(확인 후 지워주세요)
<br/>
<br/>
어떤 변경 사항이 있나요?
<br/>
> [REFACT] cjs 환경 수정, swgger 파일 디렉토리 변경

- build/swagger.yaml
- src/auth.config.ts
- src/index.ts
- src/routes/userRoutes.ts
- src/services/auth.service.ts
- src/swagger/openapi.yaml
- #68 
<br/>
- 로그인 callbackURL 배포 환경과 로컬 환경에 맞춰서 수정
<br/>
어떤 변경 사항이 있나요?
<br/>
> #68 refactor callback url

- build/swagger.yaml
- src/controllers/user.controller.ts
- src/routes/userRoutes.ts
- src/services/user.service.ts
- src/swagger/openapi.yaml
- #71 
<br/>
- 마이페이지 조회 기능
<br/>
어떤 변경 사항이 있나요?
<br/>
> #71 마이페이지 조회 기능

- prisma/schema.prisma
- src/controllers/schedule.controller.ts
- src/routes/scheduleRoutes.ts
- src/swagger/openapi.yaml
- #73 
<br/>
- 데이터베이스 필드명이 바뀜에 따라 함수 수정
- 데이터베이스 필드명을 로직에 맞게 적절히 일수를 끊어 스케줄 아이디와 함께 가져오도록 수정
<br/>
어떤 변경 사항이 있나요?
<br/>
> [REFACT] 데이터베이스 필드명 변경으로 인해 함수 수정

- build/swagger.yaml
- prisma/migrations/20250128181118_update_schedule/migration.sql
- src/auth.config.ts
- src/controllers/auth.controller.ts
- src/index.ts
- src/middlewares/auth.middleware.ts
- src/routes/authRoutes.ts
- src/routes/googleRoutes.ts
- src/routes/kakaoRoutes.ts
- src/routes/naverRoutes.ts
- src/services/auth.service.ts
- #68 
<br/>
- 클라이언트에 accessToken과 refreshToken 전달 후 Header로 요청
<br/>
어떤 변경 사항이 있나요?
<br/>
> #68 로그인 토큰 방식 변경

- @types/environment.d.ts
- src/auth.config.ts
- src/routes/googleRoutes.ts
- src/services/auth.service.ts
- src/utils/auth.utils.ts
- #85 
<br/>
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> #85 구글 클라이언트 수정

- src/controllers/exam.controller.ts
- src/index.ts
- src/repositories/exam.repository.ts
- src/routes/examRoutes.ts
- src/services/exam.service.ts
- #89 
<br/>
- 사용자가 원하는 자격증 시험 스케줄을 개인 일정에 등록
- 기존에 등록된 일정이라면 추가 방지
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> [Feature] 자격증 시험 일정 추가 기능

- build/swagger.yaml
- src/controllers/quiz.controller.ts
- src/firebase.ts
- src/index.ts
- src/repositories/quiz.repository.ts
- src/routes/quizRoutes.ts
- src/services/quiz.service.ts
[FEAT] 요구에 따른 퀴즈 보내기, 퀴즈 정답 유무 기능
- #79 
<br/>
- 사용자 요청에 따른 퀴즈 보내기, 사용자의 답과 퀴즈 데이터의 값이 일치한지 판별 
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> [FEAT] 요구에 따른 퀴즈 보내기, 퀴즈 정답 유무 기능

- build/swagger.yaml
- src/controllers/user.controller.ts
- src/routes/userRoutes.ts
- src/services/user.service.ts
- src/swagger/openapi.yaml
- #95 
<br/>
- 사용자 닉네임 수정/저장
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> #95 닉네임 수정/저장 기능

- src/controllers/schedule.controller.ts
- src/routes/scheduleRoutes.ts
- #53 
<br/>
- 특정 시험 일정의 접수 기간에 해당하면 examlink와 안내 메시지 출력
- 특정 시험 일정의 접수 기간이 지금은 아니지만 추후 예정이 있다면 가까운 일정을 가져오고 안내 메시지 출력
- 특정 시험 일정의 접수 기간이 지금이 아니며 추후에도 예정이 없다면 해당 사실을 알리며 안내 메시지 출력
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> [Feature] 자격증 시험 접수 기간 확인 및 안내 기능 #53

- src/controllers/certificationAlram.controller.ts
- src/index.ts
- src/routes/certificationAlramRoutes.ts
- src/services/certificationAlram.service.ts
- #100 
<br/>
- 전달받은 시험 일정 아이디와 자격증 아이디 값 조회
- 자격증 시험 접수 알람 생성
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> [Feature] 자격증 시험 접수 알람 생성 기능

- prisma/schema.prisma
- src/controllers/certificationAlram.controller.ts
- src/routes/certificationAlramRoutes.ts
- src/services/certificationAlram.service.ts
- #100 
<br/>
- 알람 생성 시 중복 체크 기능 추가
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> [REFACT] 시험 접수 알람 중복 체크 기능 추가 및 프리즈마 수정

- src/repositories/quiz.repository.ts
[REFACT] 과목의 유형이 하나인 시험 퀴즈처리 방식 추가
- #106 
<br/>
- 과목 유형이 하나인 시험을 저장할 수 있는 배열 및 subejct 판별 로직 수정
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> [REFACT] 과목의 유형이 하나인 시험 퀴즈처리 방식 추가

- @types/environment.d.ts
- src/controllers/auth.controller.ts
- src/index.ts
- src/middlewares/auth.middleware.ts
- src/routes/authRoutes.ts
- src/routes/certificationAlramRoutes.ts
- src/routes/examRoutes.ts
- src/routes/googleRoutes.ts
- src/routes/kakaoRoutes.ts
- src/routes/naverRoutes.ts
- src/routes/quizRoutes.ts
- src/routes/scheduleRoutes.ts
- src/routes/userRoutes.ts
- src/services/auth.service.ts
- src/utils/jwt.utils.ts
- #104 
<br/>
- jwt 토큰 관리 방식으로 변경
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
- 나중에 리프레시 토큰 갱신 방법으로 정할지 혹은 재로그인해서 jwt토큰을 발급받을지로 변경
> #104 토큰 관리 방법 수정

- src/controllers/schedule.controller.ts
- #114 
<br/>
- 기존 날짜 단순 while 반복문에서 요청받은 월의 첫째 날 혹은 마지막날까지 교집합을 구해 불필요한 반복을 줄임
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> [REFACT] 시험 기간 조회 기능 최적화

- build/swagger.yaml
- src/auth.config.ts
- src/index.ts
- src/routes/googleRoutes.ts
- src/swagger/openapi.yaml
- #116 
<br/>
- cors 수정
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> [#116] cors 설정 수정

- src/controllers/exam.controller.ts
- #120 
<br/>
- 기존에는 자격증과 일정 조회를 순차적으로 조회했는데 병렬로 조회되게끔 하여 지연 시간 개선
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> [REFACT] 시험 일정 생성 시 병렬 방식으로 DB 조회

- src/controllers/schedule.controller.ts
- src/errors.ts
- src/services/certification.service.ts
- src/services/exam.service.ts
- src/services/notification.service.ts
- src/services/schedule.service.ts
https://github.com/GonggakSim/Backend/issues/122
<br/>
- 커스텀 에러 객체 작성 후 적용
- service 계층은 순수 비즈니스 로직만 수행하도록 리팩토링
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> #122 에러 핸들링 및 에러 처리 계층 분리

- src/index.ts
- src/models/AttemptedQuiz.ts
- src/models/QuizQuestion.ts
- src/repositories/quiz.repository.ts
- src/services/quiz.service.ts
[REFACT] 퀴즈 데이터 DB 파베 -> 몽고 변경으로 인한 로직 변경
- #129 
<br/>
- 파이어스토어 -> 몽고 db로 변경 후 로직 수정 
<br/>
어떤 변경 사항이 있나요?
- [] 새로운 기능 추가
<br/>
<br/>
> [REFACT] 퀴즈 데이터 DB 파베 -> 몽고 변경으로 인한 로직 변경

- .github/workflows/deploy-main.yml
- build/swagger.yaml
- package.json
- src/controllers/auth.controller.ts
- src/controllers/user.controller.ts
- src/routes/authRoutes.ts
- src/services/auth.service.ts
- src/services/user.service.ts
- src/swagger/openapi.yaml
- src/utils/auth.utils.ts
- #128 
<br/>
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> [#128] 인증 관련 전체 api 수정

- package-lock.json
- package.json
- src/controllers/certification.controller.ts
- src/controllers/exam.controller.ts
- src/dtos/certification.dto.ts
- src/repositories/certification.respository.ts
- src/repositories/exam.repository.ts
- src/services/auth.service.ts
- src/services/exam.service.ts
- https://github.com/GonggakSim/Backend/issues/122
<br/>
- 에러 처리 통일 및 캘린더, 자격증 검색 API 리팩토링
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> [#122] 에러 처리 통일 및 캘린더, 자격증 검색 API 리팩토링

- package.json
- #134 
<br/>
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> [#134] 배포 환경 오류 수정

- .github/workflows/deploy-main.yml
- #134 
ex) #17 FEAT: pull request template 작성
(확인 후 지워주세요)
<br/>
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> [REFACT] deploy 수정

- scripts/build.ts
- #(issue 번호)
ex) #17 FEAT: pull request template 작성
(확인 후 지워주세요)
<br/>
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> #134 build bcrypt 수정

- package-lock.json
- package.json
- scripts/build.ts
- src/services/auth.service.ts
- #134 
<br/>
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> [#134] bcrypt -> bcryptjs

- package-lock.json
- package.json
- scripts/build.ts
- src/services/auth.service.ts
- #(issue 번호)
ex) #17 FEAT: pull request template 작성
(확인 후 지워주세요)
<br/>
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> [Deploy] Update bcryptejs

- src/controllers/auth.controller.ts
- src/swagger/openapi.yaml
- #144 
<br/>
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> [#144] 오타 수정

- src/repositories/user.repository.ts
- #147 
<br/>
- 사용자 정보 입력 예외 처리 수정
<br/>
어떤 변경 사항이 있나요?
<br/>
<br/>
> [#147] QA : 사용자 정보 입력 예외 처리 수정
